export enum EScreen {
  SPLASH = 'slash-screen',
  CONFIRM_POLICY = 'confirm-policy-screen',
  HOME = 'home-screen',
  SIGNUP_INFO = 'signup-info-screen',
  CONFIRM_PHONE_NUMBER = 'confirm-phone-number-screen',
  SIGNUP_BY_PHONE_NUMBER = 'signuSp-by-phone-number-screen',
  SIGNUP_BY_SOCIAL = 'signup-by-social-screen',
  MAP = 'map-screen',
  SETTINGS = 'settings-screen',
  MESSAGES = 'messages-screen',
  SEND_DISTRESS_SIGNAL = 'send-distress-signal-screen',
  DRAWER = 'drawer-screen',
  HELP = 'help-screen',
  DETAIL_MESSAGE = 'detail-message-screen',
}
