export enum EScreen {
  SPLASH = 'slash-screen',
  CONFIRM_POLICY = 'confirm-policy-screen',
  HOME = 'home-screen',
  SIGNUP_INFO = 'signup-info-screen',
  CONFIRM_PHONE_NUMBER = 'confirm-phone-number-screen',
  SIGNUP_BY_PHONE_NUMBER = 'signup-by-phone-number-screen',
  SIGNUP_BY_SOCIAL = 'signup-by-social-screen',
  MAP = 'map-screen',
  SETTINGS = 'setting-screen',
  MESSAGES = 'messages-screen',
  SEND_DISTRESS_SIGNAL = 'send-distress-signal-screen',
  DRAWER = 'drawer-screen',
  HELP = 'help-screen',
  DETAIL_MESSAGE = 'detail-message-screen',
  PENDING_MESSAGE = 'pending-message-screen',
  UPGRADE_SERVICE = 'upgrade-service-screen',
  SIGNIN_BY_EMAIL = 'signin-email-screen',
  WORKER = 'worker-screen',
  NEW_WORKER = 'new-worker-screen',
  NOTIFICATION = 'notification-screen',
  ASSIGN = 'assign-screen',
}
