export enum EUser {
  first = 'firstName',
  last = 'lastName',
  uid = 'uid',
  role = 'role',
  displayName = 'displayName',
  phoneNumber = 'phoneNumber',
  email = 'email',
  photoURL = 'photoURL',
  token = 'token',
  isAuthenticated = 'isAuthenticated',
  location = 'location',
  lastLogin = 'lastLogin',
  isRescue = 'isRescue',
}
