const DARK_BLUE_COLOR = '#1976D2';
const LIGHT_BLUE_COLOR = '#535AFF';
const WHITE_COLOR = '#FFFFFF';
const BLACK_COLOR = '#000000';
const TEXT_COLOR = '#EDF6FF';

export {
  TEXT_COLOR,
  DARK_BLUE_COLOR,
  LIGHT_BLUE_COLOR,
  WHITE_COLOR,
  BLACK_COLOR,
};
