const DART_BLUE_COLOR = '#1976D2';
const LIGHT_BLUE_COLOR = '#535AFF';
const BLACK_COLOR = '#000000';
const EXLIGHT_BLUE_COLOR = '#EDF6FF';
const WHITE_COLOR = '#FFFFFF';

export {
  DART_BLUE_COLOR,
  LIGHT_BLUE_COLOR,
  BLACK_COLOR,
  EXLIGHT_BLUE_COLOR,
  WHITE_COLOR,
};
